# Generated by Django 3.2.6 on 2024-02-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('rare', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.TextField(default='no image')),
                ('iskansai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('card', models.CharField(max_length=255)),
                ('txt', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('rare', models.IntegerField(default=0)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eemon_551_app.genre')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eemon_551_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rare', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Use', models.BooleanField()),
                ('isOwn', models.BooleanField()),
                ('buyOK', models.BooleanField()),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_users', to='eemon_551_app.title')),
                ('user_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='eemon_551_app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.BooleanField()),
                ('qes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='eemon_551_app.question')),
                ('user_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='eemon_551_app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserBackGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Use', models.BooleanField()),
                ('isOwn', models.BooleanField()),
                ('buyOK', models.BooleanField()),
                ('background_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_users', to='eemon_551_app.background')),
                ('user_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='eemon_551_app.userdata')),
            ],
        ),
    ]
