# Generated by Django 3.2.6 on 2024-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eemon_551_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbackground',
            old_name='Use',
            new_name='use',
        ),
        migrations.RenameField(
            model_name='usertitle',
            old_name='Use',
            new_name='use',
        ),
    ]
